"""Initial

Revision ID: 179e2051663c
Revises: 
Create Date: 2025-04-05 23:35:50.721419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179e2051663c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edited_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(), nullable=True),
    sa.Column('withdraw', sa.DECIMAL(), nullable=False),
    sa.Column('deposit', sa.DECIMAL(), nullable=False),
    sa.Column('balance', sa.DECIMAL(), nullable=True),
    sa.Column('new_category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(), nullable=True),
    sa.Column('withdraw', sa.DECIMAL(), nullable=False),
    sa.Column('deposit', sa.DECIMAL(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('expediency', sa.INTEGER(), nullable=True),
    sa.Column('balance', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('edited_transactions')
    # ### end Alembic commands ###
