"""Add new table

Revision ID: 53cf6e1fb0d4
Revises: 679d38767d13
Create Date: 2025-04-05 21:06:49.369472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cf6e1fb0d4'
down_revision: Union[str, None] = '679d38767d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edited_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_date', sa.DateTime(), nullable=True),
    sa.Column('withdraw', sa.DECIMAL(), nullable=False),
    sa.Column('deposit', sa.DECIMAL(), nullable=False),
    sa.Column('new_category', sa.String(), nullable=True),
    sa.Column('expediency', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edited_transactions')
    # ### end Alembic commands ###
