"""Add expediency field

Revision ID: 679d38767d13
Revises: 40ef5922b4bc
Create Date: 2025-04-05 19:48:00.129878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679d38767d13'
down_revision: Union[str, None] = '40ef5922b4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('expediency', sa.INTEGER(), nullable=True))
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'expediency')
    # ### end Alembic commands ###
